export const PRODUCTS =
[
    {
    id: 0,
    name:'Adipiscing',
    image: 'assets/img/products/ou-plant-0.png',
    category: 'exterieure, plante',
    slug:'adipiscing',
    price:'10.99',
    sku: 'ADI',
    summary:'Description Adipiscingipsum dolor sit amet descripte2',
    description:'Adipiscing ipsum dolor sit amet, consectetur adipiscing elit. Duis ullamcorper ante non vehicula eleifend. Phasellus ut feugiat tellus, vitae malesuada mi. Sed placerat ultrices enim, id fermentum ante tincidunt nec. Nulla ut mi bibendum, sodales ex ut, tempor odio. Mauris finibus elit eget ornare',
    featured: true,
},
    {
    id: 1,
    name:'Pot grey',
    image:'assets/img/products/ambiance-in-0.png',
    category: 'interieure, mobilier',
    slug:'pot-grey',
    price:'39.99',
    sku: 'POT',
    summary:'Description Pot grey dolor sit amet',
    description:'Pot grey ipsum dolor sit amet, consectetur adipiscing elit. Duis ullamcorper ante non vehicula eleifend. Phasellus ut feugiat tellus, vitae malesuada mi. Sed placerat ultrices enim, id fermentum ante tincidunt nec. Nulla ut mi bibendum, sodales ex ut, tempor odio.',    
    featured: false,
    },
    {
    id: 2,
    name:'Pot de terre',
    image: 'assets/img/products/in-plant-2.png',
    category: 'interieure, mobilier',
    slug:'pot-de-terre',
    price:'39.99',
    sku: 'POTT',
    summary:'Description Pot de terre dolor sit amet',
    description:'Pot de terre ipsum dolor sit amet, consectetur adipiscing elit. Duis ullamcorper ante non vehicula eleifend. Phasellus ut feugiat tellus, vitae malesuada mi. Sed placerat ultrices enim, id fermentum ante tincidunt nec. Nulla ut mi bibendum, sodales ex ut, tempor odio.',
    featured: false,
},
    {
    id: 3,
    name:'Raptor',
    image: 'assets/img/products/in-plant-0.png',
    category: 'interieure, plante',
    slug: 'raptor',
    price:'19.99',
    sku: 'RAP',
    summary:'Description Raptor dolor sit amet',
    description:'Raptor ipsum dolor sit amet, consectetur adipiscing elit. Duis ullamcorper ante non vehicula eleifend. Phasellus ut feugiat tellus, vitae malesuada mi. Sed placerat ultrices enim, id fermentum ante tincidunt nec. Nulla ut mi bibendum, sodales ex ut, tempor odio. Mauris finibus elit eget ornare efficitur.',
    featured: false,
},
    {
    id: 4,
    name:'Table',
    image: 'assets/img/products/ambiance-out-1.png',
    category: 'exterieure, mobilier',
    slug: 'table',
    sku: 'TAB',
    price:'29.99',
    summary:'Description Table dolor sit amet',
    description:'Table ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut feugiat tellus, vitae malesuada mi. Sed placerat ultrices enim, id fermentum ante tincidunt nec. Nulla ut mi bibendum, sodales ex ut, tempor odio. Mauris finibus elit eget ornare efficitur.',
    featured: false,
},
    {
    id: 5,
    name:'Tabouret',
    image: 'assets/img/products/ambiance-in-1.png',
    category: 'interieure, mobilier',
    slug: 'tabouret',
    sku: 'TABO',
    price:'45.99',
    summary:'Description Tabouret dolor sit amet',
    description:'Tabouret ipsum dolor sit amet, consectetur adipiscing elit. Duis ullamcorper ante non vehicula eleifend. Phasellus ut feugiat tellus, vitae malesuada mi. Sed placerat ultrices enim, id fermentum ante tincidunt nec. Nulla ut mi bibendum, sodales ex ut, tempor odio. Mauris finibus elit eget ornare efficitur.',
    featured: false,
},
    {
    id: 6,
    name:'Longtmar',
    image: 'assets/img/products/in-plant-1.png',
    category: 'exterieure, plante',
    slug: 'longtmar',
    sku: 'LON',
    price:'10.99',
    summary:'Description Longtmar dolor sit amet',
    description:'Longtmar ipsum dolor sit amet, consectetur adipiscing elit. Duis ullamcorper ante non vehicula eleifend. Phasellus ut feugiat tellus, vitae malesuada mi. Sed placerat ultrices enim, id fermentum ante tincidunt nec. Nulla ut mi bibendum, sodales ex ut, tempor odio. Mauris finibus elit eget ornare efficitur.',
    featured: false,
}
]