export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';


export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
